### ISSUE TITLE
Crash when using with first person model mod

### ISSUE THREAD

**Issue by BreadIsBest** [CammiesCorner/Arcanus#26]
First person model is the only other mod I have installed (not counting dependencies) D:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-03-11 19:54:08
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client_init' due to errors, provided by 'arcanuscontinuum'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.api.entrypoint.EntrypointUtil.invokeContainer(EntrypointUtil.java:54)
	at org.quiltmc.loader.api.entrypoint.EntrypointUtil.invoke(EntrypointUtil.java:46)
	at net.minecraft.class_310.handler$zjc000$quilt_base$onInit(class_310.java:4023)
	at net.minecraft.class_310.<init>(class_310.java:460)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchMethodError: 'boolean dev.tr7zw.firstperson.FirstPersonModelCore.showVanillaHands()'
	at dev.cammiescorner.arcanuscontinuum.common.compat.FirstPersonCompat.init(FirstPersonCompat.java:10)
	at dev.cammiescorner.arcanuscontinuum.common.compat.ArcanusCompat.ifEnabled(ArcanusCompat.java:26)
	at dev.cammiescorner.arcanuscontinuum.client.ArcanusClient.onInitializeClient(ArcanusClient.java:90)
	at org.quiltmc.loader.api.entrypoint.EntrypointUtil.lambda$invoke$1(EntrypointUtil.java:46)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.api.entrypoint.EntrypointUtil.invokeContainer(EntrypointUtil.java:54)
	at org.quiltmc.loader.api.entrypoint.EntrypointUtil.invoke(EntrypointUtil.java:46)
	at net.minecraft.class_310.handler$zjc000$quilt_base$onInit(class_310.java:4023)
	at net.minecraft.class_310.<init>(class_310.java:460)

**Comment by BreadIsBest** [comment]
Forgot to mention this is the latest 1.20.1 version

**Comment by CammiePone** [comment]
scream. why did they remove that method bruh

**Comment by BreadIsBest** [comment]
THANK YOU I LOVE YOU

**Comment by UpcraftLP** [comment]
Hehe yw ^^

**Comment by BreadIsBest** [comment]
:point_right::point_left: can you please fix that for the 1.19.2 version as well

**Comment by UpcraftLP** [comment]
> 👉👈 can you please fix that for the 1.19.2 version as well

Sorry, but the 1.19.2 version was a one-off and is very much unsupported at this point.
However, you can probably work around it by simply downgrading first person model to v2.2.2 or v2.2.3.
